### ISSUE TITLE
RFC legacy: remove search_engine dependency

### ISSUE THREAD

**Issue by hachreak** [inveniosoftware/invenio-tags#11]
#### Problem
Currently, the module use legacy `search_engine` to:
- Api:
  - detach_tag_from_record
  - attach_tags_to_record
  - attach_tag_to_record
  - get_attached_tags_on_record
- Form:
  - validate_user_can_see_bibrec

#### Question
How can we remove the dependency?

@jirikuncar

**Comment by jirikuncar** [comment]
- `record_exists` -> `invenio_records.api:get_record` or `invenio_records.model:Bibrec`
